In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from openpyxl import load_workbook
import requests

In [2]:
airnow_df = pd.read_excel("../data/AirData_Final.xlsx")

In [3]:
census = pd.read_excel('../data/Census.xlsx')
census

       city state  area_miles  year  population  density   city_state
0   Atlanta    GA     3657.47  2020     5803000  1586.62  Atlanta, GA
1   Atlanta    GA     3657.47  2021     5911000  1616.14  Atlanta, GA
2   Atlanta    GA     3657.47  2022     6013000  1644.03  Atlanta, GA
3   Atlanta    GA     3657.47  2023     6106000  1669.46  Atlanta, GA
4   Atlanta    GA     3657.47  2024     6193000  1693.25  Atlanta, GA
..      ...   ...         ...   ...         ...      ...          ...
90  Jackson    MS      639.64  2020      420000   656.62  Jackson, MS
91  Jackson    MS      639.64  2021      426000   666.00  Jackson, MS
92  Jackson    MS      639.64  2022      431000   673.82  Jackson, MS
93  Jackson    MS      639.64  2023      436000   681.63  Jackson, MS
94  Jackson    MS      639.64  2024      441000   689.45  Jackson, MS

[95 rows x 7 columns]

In [4]:
pd.set_option('display.max_columns',None)

In [5]:
aqi_annual = airnow_df.groupby(['reporting_area','state_code','year'])['AQI'].mean().reset_index()
aqi_annual

                reporting_area state_code  year        AQI
0    Aiken-Augusta - SC and GA         SC  2021  59.500000
1    Aiken-Augusta - SC and GA         SC  2022  54.000000
2    Aiken-Augusta - SC and GA         SC  2023  57.916667
3    Aiken-Augusta - SC and GA         SC  2024  61.166667
4                         Alba         MO  2019  35.666667
..                         ...        ...   ...        ...
941              Yancey County         NC  2020  46.333333
942              Yancey County         NC  2021  55.000000
943              Yancey County         NC  2022  52.750000
944              Yancey County         NC  2023  52.500000
945              Yancey County         NC  2024  48.833333

[946 rows x 4 columns]

In [6]:
aqi_annual.loc[:, 'AQI'] = airnow_df['AQI'].round().astype('Int64')
aqi_annual

                reporting_area state_code  year   AQI
0    Aiken-Augusta - SC and GA         SC  2021  42.0
1    Aiken-Augusta - SC and GA         SC  2022  41.0
2    Aiken-Augusta - SC and GA         SC  2023  28.0
3    Aiken-Augusta - SC and GA         SC  2024  36.0
4                         Alba         MO  2019  51.0
..                         ...        ...   ...   ...
941              Yancey County         NC  2020  35.0
942              Yancey County         NC  2021  55.0
943              Yancey County         NC  2022  68.0
944              Yancey County         NC  2023  35.0
945              Yancey County         NC  2024  35.0

[946 rows x 4 columns]

In [7]:
final_df = pd.merge(aqi_annual, census, left_on=['reporting_area','state_code','year'],right_on= ['city','state','year'], how="inner")

In [8]:
final_df.to_excel("../data/aqi_census.xlsx", index=False)